name: 'Add .NET Format Problem Matcher'
description: 'Add github action program matcher for `dotnet format` to add errors/warnings as annotations'
runs:
  using: "composite"
  steps:
    - name: Register Problem Matcher
      shell: bash
      run: echo "::add-matcher::${{ github.action_path }}/problem-matcher-dotnet-format.json"  
